"""Meeting Prep Companion appendix renderer.

Renders priority-ranked questions for underwriter meetings into the
Word document as an appendix. Questions are generated by walking the
AnalysisState model (see meeting_questions.py for generation logic).

Each question includes D&O context, expected good/bad answers,
source finding reference, and red flag follow-up guides.
Tagged by category: CLARIFICATION, FORWARD_INDICATOR, GAP_FILLER,
CREDIBILITY_TEST.

Organized by category with summary statistics header.

Phase 60-03: Migrated from AnalysisState to shared context dict.
"""

from __future__ import annotations

import logging
from collections import Counter
from datetime import UTC, datetime
from typing import Any

from do_uw.stages.render.design_system import DesignSystem
from do_uw.stages.render.docx_helpers import (
    add_section_divider,
    add_styled_table,
)
from do_uw.stages.render.sections.meeting_questions import (
    MeetingQuestion,
    generate_clarification_questions,
    generate_forward_indicator_questions,
)
from do_uw.stages.render.sections.meeting_questions_analysis import (
    generate_bear_case_questions,
    generate_mispricing_questions,
    generate_peril_map_questions,
)
from do_uw.stages.render.sections.meeting_questions_gap import (
    generate_credibility_test_questions,
    generate_gap_filler_questions,
)
from do_uw.stages.render.sca_counter import count_active_genuine_scas

logger = logging.getLogger(__name__)

# Category display order and labels
_CATEGORY_ORDER: list[tuple[str, str, str]] = [
    ("CREDIBILITY_TEST", "Credibility Tests", "Probe narrative coherence and management credibility"),
    ("FORWARD_INDICATOR", "Forward Indicators", "Upcoming events and deteriorating trends"),
    ("GAP_FILLER", "Gap Fillers", "Missing data that should exist for D&O analysis"),
    ("CLARIFICATION", "Clarifications", "LOW confidence data needing verification"),
]

# Category tag colors: (R, G, B) tuples
_CATEGORY_COLORS: dict[str, tuple[int, int, int]] = {
    "CLARIFICATION": (0x4A, 0x90, 0xD9),  # Blue
    "FORWARD_INDICATOR": (0xE6, 0x73, 0x00),  # Orange
    "GAP_FILLER": (0xFF, 0xB8, 0x00),  # Amber
    "CREDIBILITY_TEST": (0xCC, 0x00, 0x00),  # Red
}


def render_meeting_prep(
    doc: Any, context: dict[str, Any], ds: DesignSystem
) -> None:
    """Render the Meeting Prep Companion appendix into the Word document.

    Generates priority-ranked questions from the state model analysis.
    Questions are organized by category, each with source findings,
    expected answers, and follow-up guidance.

    Args:
        doc: The python-docx Document.
        context: Shared context dict from build_template_context().
        ds: Design system with visual constants.
    """
    from docx.enum.text import WD_PARAGRAPH_ALIGNMENT  # type: ignore[import-untyped]

    # TODO(phase-60): question generators take AnalysisState directly
    state = context["_state"]

    # Page break before appendix
    doc.add_page_break()

    # Heading
    add_section_divider(doc)
    heading: Any = doc.add_paragraph(style="DOHeading1")
    heading.add_run("Appendix: Meeting Prep Companion")

    # Introduction
    intro: Any = doc.add_paragraph(style="DOBody")
    intro.add_run(
        "The following questions are generated from the analysis data to help "
        "prepare for underwriting meetings. Questions reference specific "
        "extracted findings and are ranked by priority within each category."
    )

    # Collect all questions from 7 generators (4 original + 3 new SC5 generators)
    all_questions: list[MeetingQuestion] = []
    all_questions.extend(generate_clarification_questions(state))
    all_questions.extend(generate_mispricing_questions(state))
    all_questions.extend(generate_forward_indicator_questions(state))
    all_questions.extend(generate_bear_case_questions(state))
    all_questions.extend(generate_gap_filler_questions(state))
    all_questions.extend(generate_credibility_test_questions(state))
    all_questions.extend(generate_peril_map_questions(state))

    if not all_questions:
        para: Any = doc.add_paragraph(style="DOBody")
        run: Any = para.add_run(
            "No specific meeting prep questions generated. "
            "All data points have sufficient confidence and coverage."
        )
        run.italic = True
        return

    # Render summary statistics
    _render_summary_stats(doc, all_questions, ds)

    # Group by category and render in order
    questions_by_cat: dict[str, list[MeetingQuestion]] = {}
    for q in all_questions:
        questions_by_cat.setdefault(q.category, []).append(q)

    global_idx = 1
    for cat_id, cat_label, cat_desc in _CATEGORY_ORDER:
        cat_questions = questions_by_cat.get(cat_id, [])
        if not cat_questions:
            continue
        # Sort within category by priority descending
        cat_questions.sort(key=lambda q: q.priority, reverse=True)
        global_idx = _render_category_section(
            doc, ds, cat_id, cat_label, cat_desc, cat_questions, global_idx
        )

    # Footer note
    footer_para: Any = doc.add_paragraph(style="DOCaption")
    footer_para.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    gen_date = datetime.now(tz=UTC).strftime("%Y-%m-%d")
    footer_para.add_run(
        f"Questions generated from analysis data as of {gen_date}. "
        f"Priority reflects scoring impact and data confidence gaps."
    )

    logger.info(
        "Meeting prep appendix: %d questions in %d categories",
        len(all_questions),
        len(questions_by_cat),
    )


def _render_summary_stats(
    doc: Any, questions: list[MeetingQuestion], ds: DesignSystem
) -> None:
    """Render summary statistics table for all questions."""
    heading: Any = doc.add_paragraph(style="DOHeading3")
    heading.add_run("Question Summary")

    # Count by category
    counts: Counter[str] = Counter(q.category for q in questions)
    high_priority = sum(1 for q in questions if q.priority >= 8.0)

    rows: list[list[str]] = [
        ["Total Questions", str(len(questions))],
        ["High Priority (8+)", str(high_priority)],
    ]
    for cat_id, cat_label, _ in _CATEGORY_ORDER:
        count = counts.get(cat_id, 0)
        if count > 0:
            rows.append([cat_label, str(count)])

    add_styled_table(doc, ["Metric", "Count"], rows, ds)


def _render_category_section(
    doc: Any,
    ds: DesignSystem,
    cat_id: str,
    cat_label: str,
    cat_desc: str,
    questions: list[MeetingQuestion],
    start_idx: int,
) -> int:
    """Render a category section with its questions.

    Returns the next global question index.
    """
    from docx.shared import RGBColor  # type: ignore[import-untyped]

    # Category heading with colored tag
    cat_heading: Any = doc.add_paragraph(style="DOHeading2")
    color_rgb = _CATEGORY_COLORS.get(cat_id, (0x33, 0x33, 0x33))
    tag_run: Any = cat_heading.add_run(f"{cat_label} ")
    tag_run.font.color.rgb = RGBColor(*color_rgb)
    count_run: Any = cat_heading.add_run(f"({len(questions)})")
    count_run.font.color.rgb = ds.color_text_light

    # Category description
    desc_para: Any = doc.add_paragraph(style="DOBody")
    desc_run: Any = desc_para.add_run(cat_desc)
    desc_run.italic = True
    desc_run.font.size = ds.size_small
    desc_run.font.color.rgb = ds.color_text_light

    # Render each question
    idx = start_idx
    for q in questions:
        _render_question(doc, ds, idx, q)
        idx += 1

    return idx


def _render_question(
    doc: Any,
    ds: DesignSystem,
    idx: int,
    q: MeetingQuestion,
) -> None:
    """Render a single meeting prep question into the document."""
    from docx.shared import Pt, RGBColor  # type: ignore[import-untyped]

    # Question number + category tag
    tag_para: Any = doc.add_paragraph(style="DOHeading3")
    tag_run: Any = tag_para.add_run(f"Q{idx}. [{q.category}]")
    color_rgb = _CATEGORY_COLORS.get(q.category, (0x33, 0x33, 0x33))
    tag_run.font.color.rgb = RGBColor(*color_rgb)

    # Priority indicator
    priority_text = " (HIGH)" if q.priority >= 8.0 else ""
    if priority_text:
        p_run: Any = tag_para.add_run(priority_text)
        p_run.font.color.rgb = RGBColor(0xCC, 0x00, 0x00)
        p_run.font.size = Pt(9)

    # Question text (bold)
    q_para: Any = doc.add_paragraph(style="DOBody")
    q_run: Any = q_para.add_run(q.question)
    q_run.bold = True

    # Source finding reference
    if q.source_finding:
        src_para: Any = doc.add_paragraph(style="DOBody")
        src_label: Any = src_para.add_run("Source Finding: ")
        src_label.bold = True
        src_label.font.size = Pt(9)
        src_label.font.color.rgb = ds.color_text_light
        src_text: Any = src_para.add_run(q.source_finding)
        src_text.font.size = Pt(9)
        src_text.font.color.rgb = ds.color_text_light

    # Context
    ctx_para: Any = doc.add_paragraph(style="DOBody")
    ctx_label: Any = ctx_para.add_run("D&O Context: ")
    ctx_label.bold = True
    ctx_label.font.size = Pt(9)
    ctx_text: Any = ctx_para.add_run(q.context)
    ctx_text.font.size = Pt(9)

    # Expected answers heading
    ans_heading: Any = doc.add_paragraph(style="DOBody")
    ans_run: Any = ans_heading.add_run("Expected Answers:")
    ans_run.bold = True
    ans_run.font.size = Pt(9)

    # Good answer
    good_para: Any = doc.add_paragraph(style="DOBody")
    good_label: Any = good_para.add_run("Reassuring: ")
    good_label.bold = True
    good_label.font.size = Pt(9)
    good_label.font.color.rgb = RGBColor(0x4A, 0x90, 0xD9)
    good_text: Any = good_para.add_run(q.good_answer)
    good_text.font.size = Pt(9)
    good_para.paragraph_format.left_indent = Pt(18)

    # Bad answer
    bad_para: Any = doc.add_paragraph(style="DOBody")
    bad_label: Any = bad_para.add_run("Concerning: ")
    bad_label.bold = True
    bad_label.font.size = Pt(9)
    bad_label.font.color.rgb = RGBColor(0xCC, 0x00, 0x00)
    bad_text: Any = bad_para.add_run(q.bad_answer)
    bad_text.font.size = Pt(9)
    bad_para.paragraph_format.left_indent = Pt(18)

    # Follow-up
    fu_para: Any = doc.add_paragraph(style="DOBody")
    fu_label: Any = fu_para.add_run("If Concerning: ")
    fu_label.bold = True
    fu_label.font.size = Pt(9)
    fu_label.font.color.rgb = ds.color_text_light
    fu_text: Any = fu_para.add_run(q.follow_up)
    fu_text.font.size = Pt(9)
    fu_text.font.color.rgb = ds.color_text_light

    # Expected answer range
    if q.expected_answer_range:
        ear_para: Any = doc.add_paragraph(style="DOBody")
        ear_label: Any = ear_para.add_run("Expected Range: ")
        ear_label.bold = True
        ear_label.font.size = Pt(9)
        ear_label.font.color.rgb = ds.color_text_light
        ear_text: Any = ear_para.add_run(q.expected_answer_range)
        ear_text.font.size = Pt(9)
        ear_text.font.color.rgb = ds.color_text_light


__all__ = ["render_meeting_prep"]
